# MakeFile ProgettoSO :

progetto : #target name
	gcc -o main main.c
	gcc -o taxi taxi.c
	gcc -o request_generator request_generator.c
	gcc -o request request.c
	gcc -o new_taxi new_taxi.c
	gcc -o master master.c

	./main